
export const SEARCH_BLOCK_REQUEST='SEARCH_BLOCK_REQUEST';
export const LIST_BLOCK='LIST_BLOCK';
export const SELECTED_BLOCK='SELECTED_BLOCK';



export const LIST_TRANSACTION ='LIST_TRANSACTION';
export const SELECTED_TRANSACTION ='SELECTED_TRANSACTION';
export const SEARCH_TRANSACTION_REQUEST='SEARCH_TRANSACTION_REQUEST';

export const SEARCH_TRANSACTION_ADDRESS_REQUEST='SEARCH_TRANSACTION_ADDRESS_REQUEST';
export const SEARCH_ADDRESS_REQUEST='SEARCH_BALANCE_ADDRESS_REQUEST';
export const SELECTED_ACCOUNT='SELECTED_ACCOUNT';

export const LIST_PEER_REQUEST='LIST_PEER_REQUEST';
