export const SELECTED_IMAGE = 'SELECTED_IMAGE';
export const FLICKR_IMAGES_SUCCESS = 'FLICKR_IMAGES_SUCCESS';
export const SELECTED_VIDEO = 'SELECTED_VIDEO';
export const SHUTTER_VIDEOS_SUCCESS = 'SHUTTER_VIDEOS_SUCCESS';
export const SEARCH_MEDIA_REQUEST = 'SEARCH_MEDIA_REQUEST';
export const SEARCH_MEDIA_SUCCESS = 'SEARCH_MEDIA_SUCCESS';
export const SEARCH_MEDIA_FAILURE = 'SEARCH_MEDIA_FAILURE';

export const SEARCH_BLOCK_REQUEST='SEARCH_BLOCK_REQUEST';
export const LIST_BLOCK='LIST_BLOCK';
export const SELECTED_BLOCK='SELECTED_BLOCK';



export const LIST_TRANSACTION ='LIST_TRANSACTION';
export const SELECTED_TRANSACTION ='SELECTED_TRANSACTION';
export const SEARCH_TRANSACTION_REQUEST='SEARCH_TRANSACTION_REQUEST';

export const SEARCH_TRANSACTION_ADDRESS_REQUEST='SEARCH_TRANSACTION_ADDRESS_REQUEST';
export const SEARCH_BALANCE_SEARCH_ADDRESS_REQUEST='SEARCH_TRANSACTION_ADDRESS_REQUEST';
export const SEARCH_ADDRESS_REQUEST='SEARCH_ADDRESS_REQUEST';

export const LIST_PEER_REQUEST='LIST_PEER_REQUEST';
